#!/usr/bin/env python


from math import * 
import os


radius = 4.0
theta  = [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0]
theta  = [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
theta  = [0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0] 
# theta  = [0.0, 10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0, 90.0, 100.0, 110.0, 120.0, 130.0, 140.0, 150.0, 160.0, 170.0, 180.0]
# theta  = [0.0]
phi    = [10.0]
aov    = 40.0
width  = 500
height = 500
csv    = "data.csv"
state  = "render_samples.state"
state_begin = "render_samples_begin.state"

os.system("cat {} > {}".format(state_begin, state))

curid = 0
with open(csv, "w") as cdb, open(state, "a") as state_file:
    cdb.write("phi,theta,FILE\n")
    state_file.write("    \"Cameras\": [\n")
    for p in phi:
        for t in theta:
            cdb.write("{},{},samples_{:05d}.png\n".format(p, t, curid)) 
            if (curid != 0):
                state_file.write("      },\n")

            x = radius*sin(p)*cos(t)
            y = radius*sin(p)*sin(t)
            z = radius*cos(p)
            state_file.write("      {\n")
            state_file.write("        \"aov\"        : {},\n".format(aov))
            state_file.write("        \"viewpoint\"  : [{}, {}, {}],\n".format( x, y, z )) 
            state_file.write("        \"viewcenter\" : [0.0, 0.0, 0.0],\n" )
            state_file.write("        \"viewup\"     : [0.0, 1.0, 0.0],\n" ) 
            state_file.write("        \"dimensions\" : [{}, {}]\n".format(width, height))
            curid = curid + 1
    state_file.write("      }\n")
    state_file.write("    ]\n")
    state_file.write("}\n")
