#!/usr/bin/env python


import argparse 
import os

# global variables
APP_name = "blazar"
APP_version = "1.0"
APP_executable = "samray"

# ----------------------------------------------------------------------------
#
# parse command line options
#
# ----------------------------------------------------------------------------

epilogtext = "\n\
\n\
examples: \n\
\n\
    {} --sampler ray --input data.vol\n\
       executes the sampler using the \'ray\' sample method\n\
  \n\
".format(APP_name)

# normal option parsing
parser = argparse.ArgumentParser( 
            description="{}: a galaxy-based sampler".format(APP_name),
            epilog=epilogtext,
            add_help=True,
            formatter_class=argparse.RawDescriptionHelpFormatter )

required_args = parser.add_argument_group("required arguments")
optional_args = parser.add_argument_group("optional arguments")

required_args.add_argument(  "-i", "--input",
                    required=True,
                    help="define the input dataset for an operation")

required_args.add_argument(  "-s", "--sampler",
                    required=True,
                    help="define the sampler for an operation")

args = parser.parse_args()


command = "{} {} -r 0.025".format( args.sampler, args.input )
os.system( command )
