#!/usr/bin/env python


import os

outfile = "out.state"

preamble = '''{
    "Datasets":
    [
    ],
    "Renderer": {
    },
    "Visualizations":
    [
      {
'''

postamble = "          ]\n        }\n    ],\n"

lights    = ["data/render/visualizations/lighting/light_01.state"]
operators = [
#               "data/render/visualizations/operators/pathlines.state",
#               "data/render/visualizations/operators/samples.state",
                "data/render/visualizations/operators/slice.state",
                "data/render/visualizations/operators/volume.state"
            ]

with open(outfile, "w") as state:
    state.write(preamble)

    for l in lights:
        with open(l, 'r') as statefile:
            for line in statefile:
                state.write(line)

    state.write("        \"operators\":\n          [\n")

    numops = len(operators)
    for o in operators:
        with open(o, 'r') as statefile:
            for line in statefile:
                state.write(line)
            if (numops != 1):
                state.write(",\n")
            numops = numops - 1

    state.write(postamble)
