#!/usr/bin/env python

import os
import json
import sys

if (len(sys.argv) != 3):
    print("ERROR: need one arg: output filename")
    exit

rdef    = sys.argv[1]
outfile = sys.argv[2] 

with open(rdef) as rdef_json:
    rdata = json.load(rdef_json)

lights    = rdata["lights"] 
operators = rdata["operators"]

preamble = '''{
    "Datasets":
    [
    ],
    "Renderer": {
    },
    "Visualizations":
    [
      {
'''

postamble = "          ]\n        }\n    ],\n"

with open(outfile, "w") as state:
    state.write(preamble)

    for l in lights:
        with open(l, 'r') as statefile:
            for line in statefile:
                state.write(line)

    state.write("        \"operators\":\n          [\n")

    numops = len(operators)
    for o in operators:
        with open(o, 'r') as statefile:
            for line in statefile:
                state.write(line)
            if (numops != 1):
                state.write(",\n")
            numops = numops - 1

    state.write(postamble)
