#!/bin/bash

# clean up
OUTDIR="tmp"
rm -rf $OUTDIR
mkdir $OUTDIR

./generate_cameras render_samples_nocameras.state render.state
sampletrace sample.state render.state 

CDB="samples"
mkdir $OUTDIR/${CDB}.cdb
mv *.png $OUTDIR/${CDB}.cdb
mv data.csv $OUTDIR/${CDB}.cdb

./generate_cameras render_visualization_nocameras.state render.state
sampletrace sample.state render.state 

CDB="visualization"
mkdir $OUTDIR/${CDB}.cdb
mv *.png $OUTDIR/${CDB}.cdb
mv data.csv $OUTDIR/${CDB}.cdb



