#! /usr/bin/env python

import sys, os
import numpy as np

data = []

f = open(sys.argv[1])
f.readline()
for l in f:
	data.append([float(i) for i in l.strip().split(',')][:3])
f.close()

data = np.array(data).astype('f4')

f = open(sys.argv[1].split('.')[0] + '.xyz', 'w')
data.tofile(f)
f.close()
	
