#! /usr/bin/env python

import json, sys

if len(sys.argv) == 1:
  n = 1
else:
  n = int(sys.argv[1])

d = []
port = 1900
for i in range(factors[0]):
  for j in range(factors[1]):
    for k in range(factors[2]):
      d.append({'host': 'localhost', 'port': port})
      port = port + 1

print( json.dumps({'layout': d}) )


