#! /usr/bin/env python
## ========================================================================== ##
## Copyright (c) 2014-2018 The University of Texas at Austin.                 ##
## All rights reserved.                                                       ##
##                                                                            ##
## Licensed under the Apache License, Version 2.0 (the "License");            ##
## you may not use this file except in compliance with the License.           ##
## A copy of the License is included with this software in the file LICENSE.  ##
## If your copy does not contain the License, you may obtain a copy of the    ##
## License at:                                                                ##
##                                                                            ##
##     https://www.apache.org/licenses/LICENSE-2.0                            ##
##                                                                            ##
## Unless required by applicable law or agreed to in writing, software        ##
## distributed under the License is distributed on an "AS IS" BASIS, WITHOUT  ##
## WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.           ##
## See the License for the specific language governing permissions and        ##
## limitations under the License.                                             ##
##                                                                            ##
## ========================================================================== ##
  
import sys
from vtk import *
from vtk.util import numpy_support as ns

rdr = vtkXMLImageDataReader()
rdr.SetFileName(sys.argv[1])
rdr.Update()
o = rdr.GetOutput()
a = o.GetPointData().GetArray(sys.argv[2])
nd = ns.vtk_to_numpy(a)
if nd.dtype == 'float32':
  dtype = 'float'
elif nd.dtype == 'float64'or nd.dtype == 'int32' or nd.dtype == 'int32':
  nd = nd.astype('float32')
  dtype = 'float'
else:
  dtype = 'uchar'

tt = sys.argv[1].rsplit('.', 1)[0]
if len(tt.rsplit('-')) > 1:
  basename = sys.argv[2] + '-' + tt.rsplit('-')[1]
else:
  basename = sys.argv[2]

volname = basename + '.vol'
rawname = basename + '.raw'

of = open(rawname, 'wb')
nd.tofile(of)
of.close()

of = open(volname, 'w')
of.write('%s\n' % dtype)
of.write('%f %f %f\n' % tuple([o.GetOrigin()[j] + o.GetExtent()[2*j]*o.GetSpacing()[j] for j in range(3)]))
of.write('%d %d %d\n' % o.GetDimensions())
of.write('%f %f %f\n' % o.GetSpacing())
of.write(rawname + '\n')
of.close()


