#! /usr/bin/env python

import sys
from vtk import *
from vtk.util import numpy_support as ns

rdr = vtkXMLImageDataReader()
rdr.SetFileName(sys.argv[1])
rdr.Update()
o = rdr.GetOutput()
a = o.GetPointData().GetArray(sys.argv[2])
nd = ns.vtk_to_numpy(a)
if nd.dtype == 'float32':
  dtype = 'float'
elif nd.dtype == 'float64'or nd.dtype == 'int32' or nd.dtype == 'int32':
  nd = nd.astype('float32')
  dtype = 'float'
else:
  dtype = 'uchar'
rawname = sys.argv[1].rsplit('.', 1)[0] + '-' + sys.argv[2] + '.raw'
ospname = sys.argv[1].rsplit('.', 1)[0] + '-' + sys.argv[2] + '.osp'

of = open(rawname, 'wb')
nd.tofile(of)
of.close()

of = open(ospname, 'w')
of.write('<?xml version="1.0"?>\n')
of.write('<volume name="volume">\n')
of.write('<dimensions> %d %d %d </dimensions>\n' % o.GetDimensions())
of.write('<voxelType> float </voxelType>\n')
of.write('<samplingRate> 1.0 </samplingRate>\n')
of.write('<filename> %s </filename>\n' % rawname)
of.write('</volume>\n')
of.close()
