#! /usr/bin/env python

import json, sys

if len(sys.argv) == 1:
  n = 1
else:
  n = int(sys.argv[1])

d = []
for i in range(n):
  d.append({'host': 'localhost', 'port': 1900+i})

print( json.dumps({'layout': d}) )



